In [1]:
import numpy as np

We have some ways to manipulate the arrays, these are - 

    - numpy.concatenate(a,b)
    - numpy.vstack(a,b)
    - numpy.hstack(a,b)
    - numpy.column_stack()
    - numpy.hsplit()
    - numpy.vsplit()
    - numpy.T
    - numpy.ravel()

In [2]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(10,19).reshape(3,3)

In [5]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [8]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [9]:
np.vstack((arr1, arr2)) #you can combine any number of arrays, just the no. of rows and cols need to be same

#vstack is top and bottom (vertical) stacking

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [7]:
concatarr = np.concatenate((arr1, arr2), axis=0)  

#similar to vstack by default(axis 0) but it can do both vstack and hstack
concatarr

#concatenation = side by side concat OR top and bottom concat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [10]:
np.column_stack((arr1, arr2))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [12]:
arr_new = np.arange(20).reshape(5,4)
arr_new

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
np.vsplit(arr_new, 5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [14]:
np.hsplit(arr_new, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [15]:
#SPLITTING

big_arr = np.random.randint(50,90, size =(16,10))
big_arr

array([[67, 76, 56, 80, 74, 62, 71, 66, 70, 59],
       [72, 52, 58, 55, 78, 85, 62, 50, 77, 85],
       [76, 77, 63, 54, 66, 88, 81, 68, 71, 52],
       [61, 70, 84, 52, 50, 56, 55, 74, 66, 61],
       [68, 81, 53, 67, 50, 70, 75, 52, 86, 63],
       [64, 56, 60, 51, 69, 50, 75, 74, 52, 54],
       [53, 82, 70, 86, 80, 79, 87, 61, 83, 84],
       [67, 61, 57, 76, 83, 78, 73, 72, 62, 76],
       [70, 54, 75, 70, 85, 73, 85, 65, 65, 86],
       [85, 50, 77, 57, 89, 53, 75, 61, 80, 84],
       [88, 83, 58, 66, 80, 66, 77, 53, 88, 89],
       [61, 53, 67, 60, 83, 64, 61, 58, 50, 53],
       [72, 79, 80, 86, 83, 86, 59, 84, 65, 77],
       [55, 70, 86, 71, 72, 68, 69, 50, 54, 63],
       [88, 65, 78, 75, 57, 83, 83, 83, 87, 65],
       [87, 59, 77, 56, 70, 81, 71, 78, 60, 55]])

In [16]:
big1, big2 = np.hsplit(big_arr, 2)

In [17]:
big1

array([[67, 76, 56, 80, 74],
       [72, 52, 58, 55, 78],
       [76, 77, 63, 54, 66],
       [61, 70, 84, 52, 50],
       [68, 81, 53, 67, 50],
       [64, 56, 60, 51, 69],
       [53, 82, 70, 86, 80],
       [67, 61, 57, 76, 83],
       [70, 54, 75, 70, 85],
       [85, 50, 77, 57, 89],
       [88, 83, 58, 66, 80],
       [61, 53, 67, 60, 83],
       [72, 79, 80, 86, 83],
       [55, 70, 86, 71, 72],
       [88, 65, 78, 75, 57],
       [87, 59, 77, 56, 70]])

In [18]:
big2

array([[62, 71, 66, 70, 59],
       [85, 62, 50, 77, 85],
       [88, 81, 68, 71, 52],
       [56, 55, 74, 66, 61],
       [70, 75, 52, 86, 63],
       [50, 75, 74, 52, 54],
       [79, 87, 61, 83, 84],
       [78, 73, 72, 62, 76],
       [73, 85, 65, 65, 86],
       [53, 75, 61, 80, 84],
       [66, 77, 53, 88, 89],
       [64, 61, 58, 50, 53],
       [86, 59, 84, 65, 77],
       [68, 69, 50, 54, 63],
       [83, 83, 83, 87, 65],
       [81, 71, 78, 60, 55]])

In [19]:
big3, big4 = np.vsplit(big_arr, 2)

In [20]:
big3

array([[67, 76, 56, 80, 74, 62, 71, 66, 70, 59],
       [72, 52, 58, 55, 78, 85, 62, 50, 77, 85],
       [76, 77, 63, 54, 66, 88, 81, 68, 71, 52],
       [61, 70, 84, 52, 50, 56, 55, 74, 66, 61],
       [68, 81, 53, 67, 50, 70, 75, 52, 86, 63],
       [64, 56, 60, 51, 69, 50, 75, 74, 52, 54],
       [53, 82, 70, 86, 80, 79, 87, 61, 83, 84],
       [67, 61, 57, 76, 83, 78, 73, 72, 62, 76]])

In [21]:
big4

array([[70, 54, 75, 70, 85, 73, 85, 65, 65, 86],
       [85, 50, 77, 57, 89, 53, 75, 61, 80, 84],
       [88, 83, 58, 66, 80, 66, 77, 53, 88, 89],
       [61, 53, 67, 60, 83, 64, 61, 58, 50, 53],
       [72, 79, 80, 86, 83, 86, 59, 84, 65, 77],
       [55, 70, 86, 71, 72, 68, 69, 50, 54, 63],
       [88, 65, 78, 75, 57, 83, 83, 83, 87, 65],
       [87, 59, 77, 56, 70, 81, 71, 78, 60, 55]])

In [23]:
#Ravel and transpose
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [25]:
arr2.T      #transpose- rows become columns and columns become rows

array([[10, 13, 16],
       [11, 14, 17],
       [12, 15, 18]])

In [26]:
arr2.ravel()  
#ravel - flattens your data
#which means 3d data turns to 1d data; 2d data turns 1d--> any higher dimension turns 1d

array([10, 11, 12, 13, 14, 15, 16, 17, 18])