# Introduction to Numpy

- Stands for Numerical Python and is the Core python library for numerical computations
- Provides functionalities to make multi-dimensional arrays (1D, 2D, 3D or nD arrays)

Numpy uses 'Arrays' to handle the data
    'Arrays' is a datatype. 
Arrays are similar to lists in python
-the property here is that arrays always have homogenous data (similar data type)

- The advantages of using Numpy is Memory efficient, Faster, lot of convenience and functionalties.
- Numpy is built on C language which makes it so much faster.

In NumPy, dimensions are called **axes**. In a 2-d array above, there are two axes. 

In NumPy terminology, for 2-D arrays:
* ```axis = 0``` refers to the axis running vertically downwards across rows
* ```axis = 1``` refers to the axis running horizontally across columns


 1D Array is called Vector, 2D Array is called Matrix, nD Array is called Tensor

In [2]:
import numpy as np

## Creating Numpy Arrays 

In [3]:
##Manually creating numpy arrays

list1 = [10,20,30,40,50,60,70]  

arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60, 70])

In [4]:
arr1 * 2

array([ 20,  40,  60,  80, 100, 120, 140])

In [5]:
arr1.ndim #to show the dimension of the array

1

In [6]:
# Creating an array from a Tuple
tup = (1,2,3,4)
np.array(tup)

array([1, 2, 3, 4])

In [7]:
# Creating a 2-D Array

arr_2d = np.array([[1,2,3,4], [4,5,6,7]]) # Lists within a List
arr_2d

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [8]:
arr_2d.ndim

2

In [10]:
arr_2d.shape

(2, 4)

In [11]:
## Creating arrays using functions

The other common way is to initialise arrays using built-in functions.

The following ways are commonly used:

    np.ones(): Create array of 1s
    np.zeros(): Create array of 0s
    np.random.random(): Create array of random numbers
    np.arange(): Create array with increments of a fixed step size
    np.linspace(): Create array of fixed length
    np.diag(): Constructs a diagonal array

In [12]:
arr1 = np.arange(5, 101, 5)     #(start, stop, step)
arr1

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [14]:
arr2 = np.arange(9).reshape(3,3)

#reshape numbers should multiply to the value of the number of elements in the array
#.reshape(rows, columns)

arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
np.zeros(5, dtype = 'int')

array([0, 0, 0, 0, 0])

In [16]:
np.full((5,5), 10)  #create an array of 5x5 values where every value is 10

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [17]:
np.random.random(7)    #random data between 0-1

array([0.07362188, 0.83691654, 0.10144149, 0.05234884, 0.40340886,
       0.12010989, 0.504696  ])

In [19]:
np.random.randint(8, size = 5)  # random int between 0-8

array([7, 6, 4, 1, 4])

In [39]:
np.random.randint(4, 15, size=7)  #between 4 and 15. 7 values

array([ 6, 14, 12,  9, 11,  7, 10])

In [20]:
#create array using diag function
arr_diag = np.diag([101,202,303,404]) #constructs a diagonal array.
arr_diag

array([[101,   0,   0,   0],
       [  0, 202,   0,   0],
       [  0,   0, 303,   0],
       [  0,   0,   0, 404]])

In [21]:
# Extract diagonal values
np.diag(arr_diag)

array([101, 202, 303, 404])

### DATATYPES 

In [22]:
#You can explicitly specify which data-type you want:

a_float = np.arange(15, dtype='float')
a_float

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [25]:
d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [27]:
b = np.array([True, False, True, False])  #Boolean datatype

b.dtype

dtype('bool')

## INDEXING 

The items of an array can be accessed and assigned to the same way as other Python sequences using its index values. The index values start from 0.

     for 1d, we write like variablename[index number] OR variablename[first:second]
     for 2d, you write it as variablename[ROW index number, COL index number] 


Axis 0 is row

Axis 1 is column




In [28]:
arr_diag

array([[101,   0,   0,   0],
       [  0, 202,   0,   0],
       [  0,   0, 303,   0],
       [  0,   0,   0, 404]])

In [30]:
arr_diag[2, 2]

303

In [31]:
arr_diag[2, 1] = 33 
#assigning value
arr_diag

array([[101,   0,   0,   0],
       [  0, 202,   0,   0],
       [  0,  33, 303,   0],
       [  0,   0,   0, 404]])

## SLICING

In [33]:
#we can also combine assignment and slicing:

arr_sl = np.arange(10)
arr_sl

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr_sl[:7] = 15
arr_sl[7:] = 16
arr_sl

array([15, 15, 15, 15, 15, 15, 15, 16, 16, 16])

In [36]:
arr2 = np.arange(1,26,3).reshape(3,3)
arr2

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [37]:
arr2[0:2,1:]

array([[ 4,  7],
       [13, 16]])

In [38]:
arr2[1:, 1:] = 12
arr2

array([[ 1,  4,  7],
       [10, 12, 12],
       [19, 12, 12]])

In [40]:
arr2[0:3,1:3]

array([[ 4,  7],
       [12, 12],
       [12, 12]])

In [42]:
#if i want only one row
arr2[1]

array([10, 12, 12])

In [45]:
#if i want only one column       - the column data will come in one row array
arr2[0:3,2]

array([ 7, 12, 12])