# Numerical Operations - Numpy

## Basic Operations

In [1]:
import numpy as np

In [2]:
arr= np.arange(10,91,10).reshape(3,3)
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [3]:
#All Arithmetic Operations happen Element-wise

np.sum(arr, axis=0)

array([120, 150, 180])

In [4]:
np.sum(arr, axis=1)

array([ 60, 150, 240])

In [5]:
arr * 3

array([[ 30,  60,  90],
       [120, 150, 180],
       [210, 240, 270]])

In [10]:
arr1 = np.arange(1,10,1).reshape(3,3)
arr2 = np.arange(10,19,1).reshape(3,3)

In [11]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [21]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [13]:
arr1 * arr2

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [16]:
arr2 / arr1

array([[10.        ,  5.5       ,  4.        ],
       [ 3.25      ,  2.8       ,  2.5       ],
       [ 2.28571429,  2.125     ,  2.        ]])

In [17]:
arr1.dot(arr2) # Matrix multiplication 

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

#### Array mathematics - with functions 

In [20]:
addarr= np.add(arr1,arr2)
addarr

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [22]:
subarr = np.subtract(arr1,arr2)
subarr

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [23]:
mularr = np.multiply(arr1, arr2)
mularr

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [25]:
divarr = np.divide(arr1, arr2)
divarr

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ],
       [0.4375    , 0.47058824, 0.5       ]])

In [26]:
exparr = np.exp(arr1) # e**20
exparr

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### COMPARISONS 

In [18]:
# Element-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 3, 2, 4])

np.equal(a,c)

array([ True, False, False,  True])

In [19]:
# Array-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a,c)

True

## Calculating Min, Max, Mean, Median

In [27]:
a = np.array([1, 2, 3, 4, 5, 7])
b = np.array([5, 2, 2, 4, 6])
c = np.array([1, 2, 3, 4, 8])

In [28]:
a.mean()

3.6666666666666665

In [29]:
np.median(b)

4.0

In [30]:
c.max()

8

In [31]:
b.min()

2

In [32]:
data1 = np.random.randint(10,50, size= (8,6))
data1

array([[48, 38, 47, 17, 34, 29],
       [41, 37, 15, 36, 30, 35],
       [44, 41, 15, 38, 18, 40],
       [30, 28, 25, 11, 43, 37],
       [34, 49, 41, 36, 42, 38],
       [17, 25, 21, 15, 45, 48],
       [37, 39, 42, 36, 13, 24],
       [21, 25, 18, 17, 38, 35]])

In [34]:
np.max(data1)

49

In [33]:
np.min(data1, axis= 0) 

array([17, 25, 15, 11, 13, 24])

In [35]:
np.mean(data1)

31.9375

In [36]:
np.median(data1, axis = 1)  

array([36. , 35.5, 39. , 29. , 39.5, 23. , 36.5, 23. ])

In [37]:
np.sort(data1, axis=0)         #sorted data in asc based on cols

array([[17, 25, 15, 11, 13, 24],
       [21, 25, 15, 15, 18, 29],
       [30, 28, 18, 17, 30, 35],
       [34, 37, 21, 17, 34, 35],
       [37, 38, 25, 36, 38, 37],
       [41, 39, 41, 36, 42, 38],
       [44, 41, 42, 36, 43, 40],
       [48, 49, 47, 38, 45, 48]])